package HelloWorld;


/**
* HelloWorld/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* mercredi 4 février 2015 17 h 32 CET
*/

public interface HelloOperations 
{
  String sayHello (String name) throws HelloWorld.HelloPackage.ChaineVide;
  int addition (int a, int b) throws HelloWorld.HelloPackage.Negatif;
  int soustraction (int a, int b) throws HelloWorld.HelloPackage.Negatif;
  int multiplication (int a, int b) throws HelloWorld.HelloPackage.Negatif;
  int division (int a, int b) throws HelloWorld.HelloPackage.Negatif, HelloWorld.HelloPackage.DivisionParZero;
} // interface HelloOperations
