package HelloWorld;


/**
* HelloWorld/HelloPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* mercredi 4 février 2015 17 h 32 CET
*/

public abstract class HelloPOA extends org.omg.PortableServer.Servant
 implements HelloWorld.HelloOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("addition", new java.lang.Integer (1));
    _methods.put ("soustraction", new java.lang.Integer (2));
    _methods.put ("multiplication", new java.lang.Integer (3));
    _methods.put ("division", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HelloWorld/Hello/sayHello
       {
         try {
           String name = in.read_string ();
           String $result = null;
           $result = this.sayHello (name);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (HelloWorld.HelloPackage.ChaineVide $ex) {
           out = $rh.createExceptionReply ();
           HelloWorld.HelloPackage.ChaineVideHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // HelloWorld/Hello/addition
       {
         try {
           int a = in.read_ulong ();
           int b = in.read_ulong ();
           int $result = (int)0;
           $result = this.addition (a, b);
           out = $rh.createReply();
           out.write_ulong ($result);
         } catch (HelloWorld.HelloPackage.Negatif $ex) {
           out = $rh.createExceptionReply ();
           HelloWorld.HelloPackage.NegatifHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // HelloWorld/Hello/soustraction
       {
         try {
           int a = in.read_ulong ();
           int b = in.read_ulong ();
           int $result = (int)0;
           $result = this.soustraction (a, b);
           out = $rh.createReply();
           out.write_ulong ($result);
         } catch (HelloWorld.HelloPackage.Negatif $ex) {
           out = $rh.createExceptionReply ();
           HelloWorld.HelloPackage.NegatifHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // HelloWorld/Hello/multiplication
       {
         try {
           int a = in.read_ulong ();
           int b = in.read_ulong ();
           int $result = (int)0;
           $result = this.multiplication (a, b);
           out = $rh.createReply();
           out.write_ulong ($result);
         } catch (HelloWorld.HelloPackage.Negatif $ex) {
           out = $rh.createExceptionReply ();
           HelloWorld.HelloPackage.NegatifHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // HelloWorld/Hello/division
       {
         try {
           int a = in.read_ulong ();
           int b = in.read_ulong ();
           int $result = (int)0;
           $result = this.division (a, b);
           out = $rh.createReply();
           out.write_ulong ($result);
         } catch (HelloWorld.HelloPackage.Negatif $ex) {
           out = $rh.createExceptionReply ();
           HelloWorld.HelloPackage.NegatifHelper.write (out, $ex);
         } catch (HelloWorld.HelloPackage.DivisionParZero $ex) {
           out = $rh.createExceptionReply ();
           HelloWorld.HelloPackage.DivisionParZeroHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HelloWorld/Hello:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hello _this() 
  {
    return HelloHelper.narrow(
    super._this_object());
  }

  public Hello _this(org.omg.CORBA.ORB orb) 
  {
    return HelloHelper.narrow(
    super._this_object(orb));
  }


} // class HelloPOA
