package hellowebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-03-25T16:56:40.540+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://helloWebService/", name = "HelloWorldWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorldWS {

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "addition")
    public int addition(
        @WebParam(partName = "a", name = "a")
        int a,
        @WebParam(partName = "b", name = "b")
        int b
    ) throws EntierNegatif_Exception;

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "soustraction")
    public int soustraction(
        @WebParam(partName = "a", name = "a")
        int a,
        @WebParam(partName = "b", name = "b")
        int b
    ) throws EntierNegatif_Exception;

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "division")
    public int division(
        @WebParam(partName = "a", name = "a")
        int a,
        @WebParam(partName = "b", name = "b")
        int b
    ) throws EntierNegatif_Exception;

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "multiplication")
    public int multiplication(
        @WebParam(partName = "a", name = "a")
        int a,
        @WebParam(partName = "b", name = "b")
        int b
    ) throws EntierNegatif_Exception;
}
