
package hellowebservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-03-25T16:56:40.507+01:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "EntierNegatif", targetNamespace = "http://helloWebService/")
public class EntierNegatif_Exception extends Exception {
    
    private hellowebservice.EntierNegatif entierNegatif;

    public EntierNegatif_Exception() {
        super();
    }
    
    public EntierNegatif_Exception(String message) {
        super(message);
    }
    
    public EntierNegatif_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EntierNegatif_Exception(String message, hellowebservice.EntierNegatif entierNegatif) {
        super(message);
        this.entierNegatif = entierNegatif;
    }

    public EntierNegatif_Exception(String message, hellowebservice.EntierNegatif entierNegatif, Throwable cause) {
        super(message, cause);
        this.entierNegatif = entierNegatif;
    }

    public hellowebservice.EntierNegatif getFaultInfo() {
        return this.entierNegatif;
    }
}
