package HelloWorld.HelloPackage;

/**
* HelloWorld/HelloPackage/ChaineVideHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* mercredi 4 février 2015 17 h 32 CET
*/

public final class ChaineVideHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorld.HelloPackage.ChaineVide value = null;

  public ChaineVideHolder ()
  {
  }

  public ChaineVideHolder (HelloWorld.HelloPackage.ChaineVide initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorld.HelloPackage.ChaineVideHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorld.HelloPackage.ChaineVideHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorld.HelloPackage.ChaineVideHelper.type ();
  }

}
