package HelloWorld.HelloPackage;


/**
* HelloWorld/HelloPackage/ChaineVide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* mercredi 4 février 2015 17 h 32 CET
*/

public final class ChaineVide extends org.omg.CORBA.UserException
{

  public ChaineVide ()
  {
    super(ChaineVideHelper.id());
  } // ctor


  public ChaineVide (String $reason)
  {
    super(ChaineVideHelper.id() + "  " + $reason);
  } // ctor

} // class ChaineVide
