package HelloWorld.HelloPackage;


/**
* HelloWorld/HelloPackage/DivisionParZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* mercredi 4 février 2015 17 h 32 CET
*/

public final class DivisionParZero extends org.omg.CORBA.UserException
{

  public DivisionParZero ()
  {
    super(DivisionParZeroHelper.id());
  } // ctor


  public DivisionParZero (String $reason)
  {
    super(DivisionParZeroHelper.id() + "  " + $reason);
  } // ctor

} // class DivisionParZero
