package HelloWorld.HelloPackage;

/**
* HelloWorld/HelloPackage/DivisionParZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* mercredi 4 février 2015 17 h 32 CET
*/

public final class DivisionParZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorld.HelloPackage.DivisionParZero value = null;

  public DivisionParZeroHolder ()
  {
  }

  public DivisionParZeroHolder (HelloWorld.HelloPackage.DivisionParZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorld.HelloPackage.DivisionParZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorld.HelloPackage.DivisionParZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorld.HelloPackage.DivisionParZeroHelper.type ();
  }

}
