package HelloWorld.HelloPackage;

/**
* HelloWorld/HelloPackage/NegatifHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* mercredi 4 février 2015 17 h 32 CET
*/

public final class NegatifHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorld.HelloPackage.Negatif value = null;

  public NegatifHolder ()
  {
  }

  public NegatifHolder (HelloWorld.HelloPackage.Negatif initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorld.HelloPackage.NegatifHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorld.HelloPackage.NegatifHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorld.HelloPackage.NegatifHelper.type ();
  }

}
