package HelloWorld.HelloPackage;


/**
* HelloWorld/HelloPackage/Negatif.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* mercredi 4 février 2015 17 h 32 CET
*/

public final class Negatif extends org.omg.CORBA.UserException
{

  public Negatif ()
  {
    super(NegatifHelper.id());
  } // ctor


  public Negatif (String $reason)
  {
    super(NegatifHelper.id() + "  " + $reason);
  } // ctor

} // class Negatif
