package hellowebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-03-25T17:34:54.466+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://helloWebService/", name = "HelloWorldWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorldWS {

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "addition")
    public Complexe addition(
        @WebParam(partName = "a", name = "a")
        Complexe a,
        @WebParam(partName = "b", name = "b")
        Complexe b
    );

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "soustraction")
    public Complexe soustraction(
        @WebParam(partName = "a", name = "a")
        Complexe a,
        @WebParam(partName = "b", name = "b")
        Complexe b
    );

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "division")
    public Complexe division(
        @WebParam(partName = "a", name = "a")
        Complexe a,
        @WebParam(partName = "b", name = "b")
        Complexe b
    );

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "multiplication")
    public Complexe multiplication(
        @WebParam(partName = "a", name = "a")
        Complexe a,
        @WebParam(partName = "b", name = "b")
        Complexe b
    );

    @WebResult(name = "return", targetNamespace = "http://helloWebService/", partName = "return")
    @WebMethod(action = "toString")
    public java.lang.String toString(
        @WebParam(partName = "a", name = "a")
        Complexe a
    );
}
